name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: "0 0 * * 1,3,5"

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [12, 14]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      # - run: cp .env.example .env
      # we want to test a 'fresh' install for new users
      - run: rm -rf node_modules && rm package-lock.json
      - run: npm install
      # The apps/sources/etc in this project won't validate
      - run: rm -rf config
      - run: npm test
